# Generated by Django 3.0.8 on 2020-11-16 17:00

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drainase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surveyor', models.CharField(max_length=254)),
                ('waktu_surv', models.DateField()),
                ('no_kode', models.CharField(max_length=254)),
                ('rpru', models.CharField(max_length=254)),
                ('kemiringan', models.CharField(max_length=254)),
                ('pjg_salura', models.FloatField(default='')),
                ('lebar_salu', models.FloatField()),
                ('kedalaman', models.FloatField()),
                ('kondisi', models.CharField(max_length=254)),
                ('tahun', models.CharField(max_length=254)),
                ('anggaran', models.FloatField()),
                ('sumber_dan', models.CharField(max_length=254)),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Drainase',
            },
        ),
        migrations.CreateModel(
            name='Jalan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kelas_jln', models.CharField(default='', max_length=250)),
                ('panjang', models.FloatField(default='')),
                ('no_ruas', models.CharField(default='', max_length=250)),
                ('nama_jalan', models.CharField(default='', max_length=250)),
                ('tipe_perm', models.CharField(default='', max_length=250)),
                ('kond_jalan', models.CharField(default='', max_length=250)),
                ('lebar', models.FloatField(default='')),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Jalan',
            },
        ),
        migrations.CreateModel(
            name='JalanPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surveyor', models.CharField(max_length=254)),
                ('waktu_surv', models.DateField()),
                ('nomor_ruas', models.CharField(max_length=254)),
                ('nama_jalan', models.CharField(max_length=254)),
                ('panjang', models.CharField(max_length=254)),
                ('lebar', models.CharField(max_length=254)),
                ('tpp', models.CharField(max_length=254)),
                ('tpu', models.CharField(max_length=254)),
                ('lhr', models.CharField(max_length=254)),
                ('klasifikas', models.CharField(max_length=254)),
                ('status_adm', models.CharField(max_length=254)),
                ('tipe_permu', models.CharField(max_length=254)),
                ('kondisi_ja', models.CharField(max_length=254)),
                ('hambatan', models.CharField(max_length=254)),
                ('tahun', models.CharField(max_length=254)),
                ('anggaran', models.CharField(max_length=254)),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Kondisi Jalan',
            },
        ),
        migrations.CreateModel(
            name='Jembatan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surveyor', models.CharField(default='', max_length=254)),
                ('waktu_surv', models.DateField(default='')),
                ('nama', models.CharField(default='', max_length=254)),
                ('no_kode', models.CharField(default='', max_length=254)),
                ('pal_km', models.CharField(default='', max_length=254)),
                ('tipe_sebra', models.CharField(default='', max_length=254)),
                ('jenis_jemb', models.CharField(default='', max_length=254)),
                ('panjang', models.FloatField(default='')),
                ('lebar', models.FloatField(default='')),
                ('jml_bentan', models.FloatField(default='')),
                ('kondisi', models.CharField(default='', max_length=254)),
                ('tahun', models.CharField(default='', max_length=254)),
                ('anggaran', models.FloatField(default='')),
                ('sumber_dan', models.CharField(default='', max_length=254)),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Jembatan',
            },
        ),
        migrations.CreateModel(
            name='Kab_Sidrap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provinsi', models.CharField(max_length=40)),
                ('kecamatan', models.CharField(max_length=40)),
                ('desa', models.CharField(max_length=40)),
                ('kode2010', models.CharField(max_length=10)),
                ('provno', models.CharField(max_length=2)),
                ('kabkotno', models.CharField(max_length=2)),
                ('kecno', models.CharField(max_length=3)),
                ('desano', models.CharField(max_length=3)),
                ('kabkot', models.CharField(max_length=50)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Batas Administrasi',
            },
        ),
        migrations.CreateModel(
            name='Kesehatan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surveyor', models.CharField(default='', max_length=254)),
                ('waktu_surv', models.DateField(default='')),
                ('nama', models.CharField(default='', max_length=254)),
                ('alamat', models.CharField(default='', max_length=254)),
                ('jenis', models.CharField(default='', max_length=254)),
                ('jml_dokter', models.CharField(default='', max_length=254)),
                ('jml_perawa', models.CharField(default='', max_length=254)),
                ('jml_dosen', models.CharField(default='', max_length=254)),
                ('jml_pasien', models.CharField(default='', max_length=254)),
                ('fasilitas', models.CharField(default='', max_length=254)),
                ('kondisi', models.CharField(default='', max_length=254)),
                ('tahun_diba', models.CharField(default='', max_length=254)),
                ('anggaran', models.CharField(default='', max_length=254)),
                ('sumber_dan', models.CharField(default='', max_length=254)),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Fasilitas Kesehatan',
            },
        ),
        migrations.CreateModel(
            name='Pendidikan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surveyor', models.CharField(default='', max_length=254)),
                ('waktu_surv', models.DateField(default='')),
                ('nama', models.CharField(default='', max_length=254)),
                ('alamat', models.CharField(default='', max_length=254)),
                ('jenjang', models.CharField(default='', max_length=254)),
                ('jml_kelas', models.FloatField(default='')),
                ('jml_guru', models.FloatField(default='')),
                ('jml_siswa', models.FloatField(default='')),
                ('fasilitas', models.FloatField(default='')),
                ('tahun', models.CharField(default='', max_length=254)),
                ('anggaran', models.FloatField(default='')),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Pendidikan',
            },
        ),
    ]
