# Generated by Django 3.0.8 on 2020-11-11 05:43

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drainase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lcode', models.CharField(default=' ', max_length=50)),
                ('rpru', models.CharField(default=' ', max_length=100)),
                ('kemiringan', models.IntegerField(default=' ')),
                ('panjang_m', models.IntegerField(default=' ')),
                ('kdlmn_m', models.IntegerField(default=' ')),
                ('kondisi', models.CharField(default=' ', max_length=50)),
                ('tahun', models.IntegerField(default=' ')),
                ('kontraktor', models.CharField(default=' E', max_length=50)),
                ('surv_time', models.DateField(default=' ')),
                ('anggaran', models.IntegerField(default=' ')),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Drainase',
            },
        ),
        migrations.CreateModel(
            name='Jalan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surveyor', models.CharField(default=' ', max_length=250)),
                ('surv_time', models.DateField(default=' ')),
                ('number', models.IntegerField(default=' ')),
                ('name', models.CharField(default=' ', max_length=250)),
                ('tpp', models.CharField(default=' ', max_length=250)),
                ('tpu', models.CharField(default=' ', max_length=250)),
                ('lhr', models.IntegerField(default=' ')),
                ('status', models.CharField(default=' ', max_length=100)),
                ('surf_type', models.CharField(default=' ', max_length=100)),
                ('kondisi', models.CharField(default=' ', max_length=100)),
                ('hambatan', models.CharField(default=' ', max_length=100)),
                ('tahun', models.IntegerField(default=' ')),
                ('length_km', models.IntegerField(default=' ')),
                ('width_m', models.IntegerField(default=' ')),
                ('anggaran', models.IntegerField(default=' ')),
                ('klas_ruas', models.CharField(default=' ', max_length=250)),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Jalan',
            },
        ),
        migrations.CreateModel(
            name='Jembatan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surveyor', models.CharField(default=' ', max_length=100)),
                ('surv_date', models.DateField(default=' ')),
                ('nama', models.CharField(default=' ', max_length=100)),
                ('pal_km', models.IntegerField(default=' ')),
                ('bentang', models.IntegerField(default=' ')),
                ('tipe_jem', models.CharField(default=' ', max_length=100)),
                ('penyebrang', models.CharField(default=' ', max_length=100)),
                ('bhn_konstr', models.CharField(default=' ', max_length=50)),
                ('kondisi', models.CharField(default=' ', max_length=100)),
                ('tahun', models.IntegerField(default=' ')),
                ('panjang_m', models.IntegerField(default=' ')),
                ('lebar_m', models.IntegerField(default=' ')),
                ('anggaran', models.IntegerField(default=' ')),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Jembatan',
            },
        ),
        migrations.CreateModel(
            name='Kab_Sidrap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provinsi', models.CharField(default=' ', max_length=40)),
                ('kecamatan', models.CharField(default=' ', max_length=40)),
                ('desa', models.CharField(default=' ', max_length=40)),
                ('kode2010', models.CharField(default=' ', max_length=10)),
                ('provno', models.CharField(default=' ', max_length=2)),
                ('kabkotno', models.CharField(default=' ', max_length=2)),
                ('kecno', models.CharField(default=' ', max_length=3)),
                ('desano', models.CharField(default=' ', max_length=3)),
                ('kabkot', models.CharField(default=' ', max_length=50)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Batas Administrasi',
            },
        ),
        migrations.CreateModel(
            name='Kesehatan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namobj', models.CharField(default=' ', max_length=250)),
                ('remark', models.CharField(default=' ', max_length=250)),
                ('alamat', models.CharField(default=' ', max_length=250)),
                ('jml_dktr', models.IntegerField(default=' ')),
                ('jml_prwt', models.IntegerField(default=' ')),
                ('jml_pasien', models.IntegerField(default=' ')),
                ('jml_ruang', models.IntegerField(default=' ')),
                ('fasilitas', models.CharField(default=' ', max_length=250)),
                ('kond_bgnn', models.CharField(default=' ', max_length=100)),
                ('tahun', models.IntegerField(default=' ')),
                ('sumb_dana', models.CharField(default=' ', max_length=50)),
                ('kontraktor', models.CharField(default=' ', max_length=100)),
                ('surv_time', models.DateField(default=' ')),
                ('anggaran', models.IntegerField(default=' ')),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Fasilitas Kesehatan',
            },
        ),
        migrations.CreateModel(
            name='Pendidikan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namobj', models.CharField(max_length=250)),
                ('remark', models.CharField(max_length=250)),
                ('alamat', models.CharField(max_length=50)),
                ('jml_kelas', models.IntegerField(default=' ')),
                ('jml_guru', models.IntegerField(default=' ')),
                ('jml_siswa', models.IntegerField(default=' ')),
                ('fasilitas', models.CharField(max_length=254)),
                ('thn_bangun', models.IntegerField(default=' ')),
                ('surveyor', models.CharField(max_length=50)),
                ('surv_time', models.DateField()),
                ('anggaran', models.IntegerField(default=' ')),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Pendidikan',
            },
        ),
    ]
